### ISSUE TITLE
Sharp in strings

### ISSUE THREAD

**Issue by Bibobu** [brunoduran/language-lammps#1]
Hello, just opening an issue to signal that the # character contained inside a string delimited by quotes triggers the colouring into comment colour for the rest of the line.

This can cause issues while writing headers for output files. For example consider the following:
fix     BDH all ave/histo 1 1 1 0 1 100 c_Mycompute ave running file bd.hist &
        start 500 title1 "**# Bond distrance histogram" mode vector**

The bold part will be considered as a comment while "mode vector" is actually an input for the fix.

Thanks for considering the issue if you have time.

Regards.

**Comment by duran** [comment]
Hi @Bibobu !


Sorry for taking so long to reply, somehow I did not see this message. I stopped using Atom (and LAMMPS) altogether soon after making this package. I cannot recall well how Atom packages work and I have no interested in learning it again.

If you have some time you feel like trying play with the regex rules in [lammps.cson](https://github.com/brunoduran/language-lammps/blob/master/grammars/lammps.cson) (that uses [Oniguruma](https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines)) and follow any [TextMate tutorial about language support](https://developmentality.wordpress.com/2011/02/08/textmate-introduction-to-language-grammars/).

Best wishes and sorry again for a negative reply,

Bruno
